name: Build and Release Windows Executable

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Build and Release for Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Generate rsrc.syso
        run: |
          wget https://github.com/akavel/rsrc/releases/latest/download/rsrc_linux_amd64 -O rsrc
          chmod +x rsrc
          ./rsrc -ico favicon.ico

      - name: Check for rsrc.syso
        run: |
          echo "Checking if rsrc.syso exists..."
          if [ ! -f "rsrc.syso" ]; then
            echo "Error: rsrc.syso is missing!"
            exit 1
          fi

      - name: Get short commit SHA
        id: commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Define release tag
        id: version
        run: echo "tag_name=v${{ env.date }}-${{ env.sha_short }}" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.tag_name }}
          git push origin ${{ env.tag_name }}

      - name: Build Windows Executable
        run: |
          GOOS=windows GOARCH=amd64 go build -ldflags="-H windowsgui -extldflags=-static" -o stayAlive.exe main.go

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag_name }}
          name: Release ${{ env.tag_name }}
          files: stayAlive.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}